Version: v1
kind: Service
metadata:
  name: ingress-controller-service
  namespace: ingress
spec:
  type: NodePort
  ports:
  - name: http
    port: 8080
    targetPort: 80
    nodePort: 30080
    protocol: TCP
  selector:
    k8s-app: nginx-ingress-controller
