apiVersion: v1
kind: Service
metadata:
  labels:
    app: cassandra
  name: cassandra-cql
spec:
  clusterIP: 
  type: NodePort
  ports:
    - port: 9042
      name: cql
  selector:
    app: cassandra
